"""Subagent: upload Creatomate renders to YouTube via Composio

This module provides a single high-level function `upload_rendered_video_to_youtube`
that accepts a Creatomate render URL (the `url` returned by the Creatomate render API),
validates the file, optionally re-encodes it to H.264+AAC (using ffmpeg), and then
uploads it to YouTube using the Composio `YOUTUBE_UPLOAD_VIDEO` tool.

Behavior summary:
- If allowed, attempts to let Composio fetch the remote URL directly (server-side).
- If remote file appears to use non-standard codecs (or server-side fetch is disabled),
  the subagent downloads the file, probes codecs (ffprobe), re-encodes (ffmpeg) if
  necessary, and uploads the local file path to Composio.

Requirements:
- `composio` Python package available (already used elsewhere in this repo).
- Optional but recommended: `ffprobe` and `ffmpeg` on PATH for codec probing and re-encoding.

Usage example:
    from subagents.youtube_subagent import upload_rendered_video_to_youtube

    result = upload_rendered_video_to_youtube(
        render_url="https://cdn.creatomate.com/renders/....mp4",
        title="My Video",
        description="Generated by FDWA agent",
        tags=["AI","FDWA"],
        categoryId="22",
        connected_account_id=os.getenv("YOUTUBE_CONNECTED_ACCOUNT_ID")
    )

The function returns the raw Composio response dict (with `successful`, `data`, `error`).
"""

from typing import Optional, List, Dict
import os
import tempfile
import requests
import structlog
from composio import Composio
from config import config
from utils.video_utils import probe_codecs, reencode_to_h264_aac

logger = structlog.get_logger(__name__)


def _download_to_temp(url: str, min_size: int = 1000) -> Optional[str]:
    """Download a remote URL to a temporary .mp4 file and return path.

    Returns None on error.
    """
    try:
        r = requests.get(url, stream=True, timeout=60)
        if r.status_code != 200:
            logger.error("Failed to download render", status=r.status_code)
            return None

        # Write to temp file
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as tf:
            for chunk in r.iter_content(chunk_size=64 * 1024):
                if chunk:
                    tf.write(chunk)
            temp_path = tf.name

        size = os.path.getsize(temp_path)
        logger.info("Downloaded render", path=temp_path, size=size)
        if size < min_size:
            logger.error("Downloaded file too small", size=size)
            try:
                os.unlink(temp_path)
            except Exception:
                pass
            return None

        return temp_path
    except Exception as e:
        logger.error("Download failed", error=str(e))
        return None


def upload_rendered_video_to_youtube(
    render_url: str,
    title: str,
    description: str,
    tags: Optional[List[str]] = None,
    categoryId: str = "22",
    connected_account_id: Optional[str] = None,
    reencode_before_upload: bool = True,
    allow_remote_fetch: bool = True,
    composio_version: Optional[str] = None,
) -> Dict:
    """Upload a Creatomate render to YouTube via Composio.

    Args:
        render_url: URL returned by Creatomate render (mp4)
        title: YouTube title
        description: YouTube description
        tags: list of tags
        categoryId: YouTube category ID (default: 22 - People & Blogs)
        connected_account_id: Composio connected account id for YouTube
        reencode_before_upload: if True, will re-encode to H.264 + AAC when needed
        allow_remote_fetch: if True (default) tries to let Composio fetch remote URL
        composio_version: optional tool version override

    Returns:
        Composio tool response (dict) with keys `successful`, `data`, `error`.
    """

    composio_client = Composio(api_key=config.composio_api_key)
    connected_account_id = connected_account_id or os.getenv("YOUTUBE_CONNECTED_ACCOUNT_ID")
    tags = tags or []
    version = composio_version or os.getenv("YOUTUBE_TOOL_VERSION", "20251027_00")

    # 1) If remote fetch allowed, try to probe remote codecs and use remote URL when safe
    if allow_remote_fetch:
        try:
            remote_info = probe_codecs(render_url)
            if remote_info:
                streams = remote_info.get("streams", [])
                vcodec = next((s.get("codec_name") for s in streams if s.get("codec_type") == "video"), None)
                acodec = next((s.get("codec_name") for s in streams if s.get("codec_type") == "audio"), None)
                logger.info("Remote codec probe", video=vcodec, audio=acodec)

                if (vcodec and vcodec.lower() in ("h264", "avc1")) and (acodec and acodec.lower() in ("aac",)):
                    # safe to let server fetch
                    youtube_args = {
                        "categoryId": categoryId,
                        "description": description,
                        "privacyStatus": "public",
                        "tags": tags,
                        "title": title,
                        "videoFilePath": render_url,
                    }
                    logger.info("Using remote render URL for Composio upload")
                    result = composio_client.tools.execute(
                        slug="YOUTUBE_UPLOAD_VIDEO",
                        arguments=youtube_args,
                        connected_account_id=connected_account_id,
                        version=version,
                    )
                    return result
                else:
                    logger.info("Remote codecs not recommended; will download and (re-)encode locally")

        except Exception as e:
            logger.warning("Remote probe failed, falling back to download", error=str(e))

    # 2) Download locally and upload local path
    local_path = _download_to_temp(render_url)
    if not local_path:
        return {"successful": False, "error": "Failed to download render", "data": {}}

    try:
        # probe codecs
        codec_info = probe_codecs(local_path)
        vcodec = None
        acodec = None
        if codec_info:
            streams = codec_info.get("streams", [])
            vcodec = next((s.get("codec_name") for s in streams if s.get("codec_type") == "video"), None)
            acodec = next((s.get("codec_name") for s in streams if s.get("codec_type") == "audio"), None)
            logger.info("Local codec probe", video=vcodec, audio=acodec)

        # Decide to reencode if requested and codecs are not standard
        need_reencode = False
        if reencode_before_upload:
            if vcodec and vcodec.lower() not in ("h264", "avc1"):
                need_reencode = True
            if acodec and acodec.lower() not in ("aac",):
                need_reencode = True

        upload_path = local_path
        if need_reencode:
            reencoded = reencode_to_h264_aac(local_path)
            if reencoded:
                upload_path = reencoded
                try:
                    os.unlink(local_path)
                except Exception:
                    pass

        youtube_args = {
            "categoryId": categoryId,
            "description": description,
            "privacyStatus": "public",
            "tags": tags,
            "title": title,
            "videoFilePath": upload_path,
        }

        logger.info("Uploading local file to Composio", path=upload_path)
        result = composio_client.tools.execute(
            slug="YOUTUBE_UPLOAD_VIDEO",
            arguments=youtube_args,
            connected_account_id=connected_account_id,
            version=version,
        )

        return result

    finally:
        # cleanup any reencoded or downloaded files
        try:
            if os.path.exists(local_path):
                os.unlink(local_path)
        except Exception:
            pass
